### ISSUE TITLE
[General] We need to add users to the Bacalhau team for Grafana

### ISSUE THREAD

**Issue by aronchick** [protocol/netops-guild#56]
Just so folks can get access and make changes.

### Who is the DRI?
aronchick

### Team and command structure
Bacalhau - aronchick

### Estimated monthly cost
$0
  
### What else do we need to know?
Here's the list of folks

@aronchick
[David Aronchick](https://github.com/orgs/bacalhau-project/people/aronchick)
aronchick
2FA 
Owner
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40aronchick)

@binocarlos
[Kai Davenport](https://github.com/orgs/bacalhau-project/people/binocarlos)
binocarlos
2FA 
 Private
Member
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40binocarlos)

@DeveloperAlly
[Alison Haire](https://github.com/orgs/bacalhau-project/people/DeveloperAlly)
DeveloperAlly
2FA 
 Private
Member
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40DeveloperAlly)

@enricorotundo
[Enrico Rotundo](https://github.com/orgs/bacalhau-project/people/enricorotundo)
enricorotundo
2FA 
 Private
Owner
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40enricorotundo)

@fakela
[Favour Kelvin](https://github.com/orgs/bacalhau-project/people/fakela)
fakela
2FA 
 Private
Owner
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40fakela)

@[it09](https://github.com/orgs/bacalhau-project/people/it09)
it09
it09
2FA 
 Private
Owner
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40it09)

@[lukemarsden](https://github.com/orgs/bacalhau-project/people/lukemarsden)
lukemarsden
2FA 
 Private
Owner
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40lukemarsden)

@philwinder
[Phil Winder](https://github.com/orgs/bacalhau-project/people/philwinder)
philwinder
2FA 
 Private
Owner
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40philwinder)

@[ricmk](https://github.com/orgs/bacalhau-project/people/ricmk)
ricmk
2FA 
 Private
Owner
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40ricmk)

@simonwo
[Simon Worthington](https://github.com/orgs/bacalhau-project/people/simonwo)
simonwo
2FA 
 Private
Member
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40simonwo)

@wdbaruni
[Walid Baruni](https://github.com/orgs/bacalhau-project/people/wdbaruni)
wdbaruni
2FA 
 Private
Owner
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40wdbaruni)

@wesfloyd
[Wes Floyd](https://github.com/orgs/bacalhau-project/people/wesfloyd)
wesfloyd
2FA 
 Private
Owner
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40wesfloyd)

@wjam
[Will May](https://github.com/orgs/bacalhau-project/people/wjam)
wjam
2FA 
 Private
Member
[1 team](https://github.com/orgs/bacalhau-project/teams?query=%40wjam)

**Comment by placer14** [comment]
For completeness, this conversation was had:

There are two bacalhau teams in Grafana.

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/305332/213762501-f973ae8b-73bf-45c8-a378-d6429af2e586.png">

The 1 role on the first team is "Public Dashboard Writer".

- Do you know which team you want them added to? 
- Do you think the other team should be destroyed?
  - @aronchick responded: Oh! yeah, we only need the one - we just need a bunch of writers

I've made @aronchick the admin of [the bacalhau team](https://protocollabs.grafana.net/org/teams/edit/9) (which @enricorotundo already appears to be admin of). This team is admin to RW in [the newly created Bacalhau dashboard folder](https://protocollabs.grafana.net/dashboards/f/TcgtuOoVk/bacalhau-dri-ataronchick).

For simplicity, I've also removed the other team.

@aronchick Please provide the email addresses of these users. I checked these and I cannot find them and probably need to be invited. (I can only invite protocol.ai emails. External emails will need additional approval that I'm not comfortable providing.) @wdbaruni was the only use already in Grafana. I've added him to that team as a member.

**Comment by aronchick** [comment]
OK - so this looks great, but the question is can i add these folks as admins

or do you have to add them in the system and then i can add them to this

**Comment by aronchick** [comment]
Enrico Rotundo <enrico@winder.ai>, favourkelvin17@gmail.com, Iryna Tsimashenka <iryna.tsimashenka@protocol.ai>, Kai Davenport <kaiyadavenport@gmail.com>, Luke Marsden <luke@mlops.consulting>, Phil Winder <phil@winder.ai>, Richard McKnight <richard.mcknight@protocol.ai>, simon@register-dynamics.co.uk, Walid Baruni <walid.baruni@protocol.ai>, Wes Floyd <wesfloyd@protocol.ai>, will.may@opencredo.com

**Comment by placer14** [comment]
> can i add these folks as admins

@aronchick As admin of the bacalhau team, you will be able to add/remove from there as needed, which will give perms within the bacalhau folder (both linked above).

---

There are some implications and I wanted to get a "gut check" from NetOps. I'm raising this concern more broadly for discussion (and within Slack). However, I do not wish to block productivity for this discussion to complete. For lack of a clear direction otherwise, my default action is that I send these invites out at the end of today. Once accepted by the invitees, I remove all permissions and add them to the "Bacalhau" team to inherit all of it's permission.) I think risk in the short term is very low and we can undo these changes as needed.

### From the perspective of security:
Grafana is a shared resource managed by several individuals. With PL-only accounts, a misconfiguration gives sensitive info to a labber. However, by bringing in third-party accounts, I worry that a (later) misconfiguration represents a much bigger risk. Given that Grafana is a resourced shared across PL, I wanted to run this by someone "upstream" on behalf of Infra as a "gut check" that this isn't going to be a concern. I might also run this by the #security-forum (in PL Slack) a bit later today.

### From an billing/overhead perspective:
Given our recent belt-tightening, I want to be sure we're (still) okay with paying for external (to PL) seats. All of these accounts are in the same bucket and individual administration is not something managed too often after initial setup. I thought checking with someone "upstream" on behalf of Infra might be a good idea. I can run this up within NetOps instead.
I'm not feeling so comfortable making these sorts of risk assessments independently. Welcoming thoughts.

**Comment by placer14** [comment]
@aronchick I've sent the following invitations. The ones indicated as "(already a member)" did not need an invite and were added to the `Bacalhau` team. Once the invites are accepted, you should be able to add them to the team yourself.

- enrico@winder.ai (already a member)
- [x] favourkelvin17@gmail.com
- [x] iryna.tsimashenka@protocol.ai
- [x] kaiyadavenport@gmail.com
- luke@mlops.consulting (already a member)
- [x] phil@winder.ai
- [x] richard.mcknight@protocol.ai
- [x] simon@register-dynamics.co.uk
- walid.baruni@protocol.ai (already a member)
- [x] wesfloyd@protocol.ai
- [x] will.may@opencredo.com

I don't think you need anything else form me at this point, but please re-open if there's anything I missed or you can't do. 🙇

**Comment by wdbaruni** [comment]
Hi Mike, I do see that I have a viewer role, but that has very limited permissions related to our work, specifically not being able to access the Explore feature
https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/

Is it possible to grant us editor permissions as well?
